<?php

namespace Database\Seeders;

use App\Models\Car;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Storage;


class CarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //

        $sourcePath = public_path('frontend/img/cars/');
        $destinationPath = 'public/cars/images/';

        $cars = [
            [
                'id' => '1',
                'nama_mobil' => 'Suzuki Ertiga',
                'slug' => 'suzuki-ertiga',
                'type_id' => '1',
                'price' => '450000',
                'pintu' => '5',
                'penumpang' => '6',
                'description' => 'Suzuki Ertiga',
                'image1' => 'mpv-suzuki-ertiga-1.png',
                'image2' => 'mpv-suzuki-ertiga-2.png',
                'image3' => 'mpv-suzuki-ertiga-3.png',
                'image4' => 'mpv-suzuki-ertiga-4.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '2',
                'nama_mobil' => 'Toyota Calya',
                'slug' => 'toyota-calya',
                'type_id' => '1',
                'price' => '400000',
                'pintu' => '5',
                'penumpang' => '6',
                'description' => 'Toyota Calya',
                'image1' => 'mpv-toyota-calya-1.png',
                'image2' => 'mpv-toyota-calya-2.png',
                'image3' => 'mpv-toyota-calya-3.png',
                'image4' => 'mpv-toyota-calya-4.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '3',
                'nama_mobil' => 'Toyota Innova',
                'slug' => 'toyota-innova',
                'type_id' => '1',
                'price' => '550000',
                'pintu' => '5',
                'penumpang' => '8',
                'description' => 'Toyota Innova',
                'image1' => 'mpv-toyota-innova-1-hitam.png',
                'image2' => 'mpv-toyota-innova-2-hitam.png',
                'image3' => 'mpv-toyota-innova-3-hitam.png',
                'image4' => 'mpv-toyota-innova-4-hitam.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '4',
                'nama_mobil' => 'Toyota Innova',
                'slug' => 'toyota-innova',
                'type_id' => '1',
                'price' => '550000',
                'pintu' => '5',
                'penumpang' => '8',
                'description' => 'Toyota Innova',
                'image1' => 'mpv-toyota-innova-1-putih.png',
                'image2' => 'mpv-toyota-innova-2-putih.png',
                'image3' => 'mpv-toyota-innova-3-putih.png',
                'image4' => 'mpv-toyota-innova-4-putih.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '5',
                'nama_mobil' => 'Toyota Venturer',
                'slug' => 'toyota-venturer',
                'type_id' => '1',
                'price' => '500000',
                'pintu' => '5',
                'penumpang' => '8',
                'description' => 'Toyota Venturer',
                'image1' => 'mpv-toyota-venturer-1-abu.png',
                'image2' => 'mpv-toyota-venturer-2-abu.png',
                'image3' => 'mpv-toyota-venturer-3-abu.png',
                'image4' => 'mpv-toyota-venturer-4-abu.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '6',
                'nama_mobil' => 'Toyota Venturer',
                'slug' => 'toyota-venturer',
                'type_id' => '1',
                'price' => '500000',
                'pintu' => '5',
                'penumpang' => '8',
                'description' => 'Toyota Venturer',
                'image1' => 'mpv-toyota-venturer-1-putih.png',
                'image2' => 'mpv-toyota-venturer-2-putih.png',
                'image3' => 'mpv-toyota-venturer-3-putih.png',
                'image4' => 'mpv-toyota-venturer-4-putih.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '7',
                'nama_mobil' => 'Daihatsu Terios',
                'slug' => 'daihatsu-terios',
                'type_id' => '2',
                'price' => '500000',
                'pintu' => '5',
                'penumpang' => '8',
                'description' => 'Daihatsu Terios',
                'image1' => 'suv-daihatsu-terios-1.png',
                'image2' => 'suv-daihatsu-terios-2.png',
                'image3' => 'suv-daihatsu-terios-3.png',
                'image4' => 'suv-daihatsu-terios-4.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '8',
                'nama_mobil' => 'Honda BRV',
                'slug' => 'honda-brv',
                'type_id' => '2',
                'price' => '500000',
                'pintu' => '5',
                'penumpang' => '8',
                'description' => 'Honda BRV',
                'image1' => 'suv-honda-brv-1-hitam.png',
                'image2' => 'suv-honda-brv-2-hitam.png',
                'image3' => 'suv-honda-brv-3-hitam.png',
                'image4' => 'suv-honda-brv-4-hitam.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '9',
                'nama_mobil' => 'Honda BRV',
                'slug' => 'honda-brv',
                'type_id' => '2',
                'price' => '500000',
                'pintu' => '5',
                'penumpang' => '8',
                'description' => 'Honda BRV',
                'image1' => 'suv-honda-brv-1-putih.png',
                'image2' => 'suv-honda-brv-2-putih.png',
                'image3' => 'suv-honda-brv-3-putih.png',
                'image4' => 'suv-honda-brv-4-putih.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '10',
                'nama_mobil' => 'Honda CRV',
                'slug' => 'honda-crv',
                'type_id' => '2',
                'price' => '500000',
                'pintu' => '5',
                'penumpang' => '4',
                'description' => 'Honda CRV',
                'image1' => 'suv-honda-crv-1.png',
                'image2' => 'suv-honda-crv-2.png',
                'image3' => 'suv-honda-crv-3.png',
                'image4' => 'suv-honda-crv-4.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '11',
                'nama_mobil' => 'Honda HRV',
                'slug' => 'honda-hrv',
                'type_id' => '2',
                'price' => '500000',
                'pintu' => '5',
                'penumpang' => '4',
                'description' => 'Honda HRV',
                'image1' => 'suv-honda-hrv-1.png',
                'image2' => 'suv-honda-hrv-2.png',
                'image3' => 'suv-honda-hrv-3.png',
                'image4' => 'suv-honda-hrv-4.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '12',
                'nama_mobil' => 'Honda WRV',
                'slug' => 'honda-wrv',
                'type_id' => '2',
                'price' => '500000',
                'pintu' => '5',
                'penumpang' => '4',
                'description' => 'Honda WRV',
                'image1' => 'suv-honda-wrv-1.png',
                'image2' => 'suv-honda-wrv-2.png',
                'image3' => 'suv-honda-wrv-3.png',
                'image4' => 'suv-honda-wrv-4.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '13',
                'nama_mobil' => 'Honda CRV',
                'slug' => 'honda-crv',
                'type_id' => '2',
                'price' => '500000',
                'pintu' => '5',
                'penumpang' => '4',
                'description' => 'Honda CRV',
                'image1' => 'suv-honda-crv-1.png',
                'image2' => 'suv-honda-crv-2.png',
                'image3' => 'suv-honda-crv-3.png',
                'image4' => 'suv-honda-crv-4.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '14',
                'nama_mobil' => 'Mitsubishi Xpander',
                'slug' => 'mitsubishi-xpander',
                'type_id' => '2',
                'price' => '500000',
                'pintu' => '5',
                'penumpang' => '8',
                'description' => 'Mitsubishi Xpander',
                'image1' => 'suv-mitsubishi-xpander-1.png',
                'image2' => 'suv-mitsubishi-xpander-2.png',
                'image3' => 'suv-mitsubishi-xpander-3.png',
                'image4' => 'suv-mitsubishi-xpander-4.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '15',
                'nama_mobil' => 'Toyota Fortuner',
                'slug' => 'toyota-fortuner',
                'type_id' => '2',
                'price' => '500000',
                'pintu' => '5',
                'penumpang' => '8',
                'description' => 'Toyota Fortuner',
                'image1' => 'suv-toyota-fortuner-1.png',
                'image2' => 'suv-toyota-fortuner-2.png',
                'image3' => 'suv-toyota-fortuner-3.png',
                'image4' => 'suv-toyota-fortuner-4.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '16',
                'nama_mobil' => 'Honda Jazz',
                'slug' => 'honda-jazz',
                'type_id' => '3',
                'price' => '400000',
                'pintu' => '5',
                'penumpang' => '4',
                'description' => 'Honda Jazz',
                'image1' => 'hatchback-honda-jazz-1.png',
                'image2' => 'hatchback-honda-jazz-2.png',
                'image3' => 'hatchback-honda-jazz-3.png',
                'image4' => 'hatchback-honda-jazz-4.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '17',
                'nama_mobil' => 'Honda Accord',
                'slug' => 'honda-accord',
                'type_id' => '4',
                'price' => '400000',
                'pintu' => '5',
                'penumpang' => '4',
                'description' => 'Honda Accord',
                'image1' => 'sedan-honda-accord-1.png',
                'image2' => 'sedan-honda-accord-2.png',
                'image3' => 'sedan-honda-accord-3.png',
                'image4' => 'sedan-honda-accord-4.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '18',
                'nama_mobil' => 'Honda City',
                'slug' => 'honda-city',
                'type_id' => '4',
                'price' => '400000',
                'pintu' => '5',
                'penumpang' => '4',
                'description' => 'Honda City',
                'image1' => 'sedan-honda-city-1.png',
                'image2' => 'sedan-honda-city-2.png',
                'image3' => 'sedan-honda-city-3.png',
                'image4' => 'sedan-honda-city-4.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '19',
                'nama_mobil' => 'Toyota Camry',
                'slug' => 'toyota-camry',
                'type_id' => '4',
                'price' => '400000',
                'pintu' => '5',
                'penumpang' => '4',
                'description' => 'Toyota Camry',
                'image1' => 'sedan-toyota-camry-1.png',
                'image2' => 'sedan-toyota-camry-2.png',
                'image3' => 'sedan-toyota-camry-3.png',
                'image4' => 'sedan-toyota-camry-4.png',
                'status' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
        ];


        foreach ($cars as &$car) {
            // Iterate over each image
            for ($i = 1; $i <= 4; $i++) {
                $imageKey = 'image' . $i;

                // Get source and destination paths for the current image
                $sourceFile = $sourcePath . $car[$imageKey];
                $destinationFile = $destinationPath . basename($car[$imageKey]); // Ambil bagian akhir jalur gambar

                // Check if the destination file doesn't exist
                if (!Storage::exists($destinationFile)) {
                    // Copy the image to the destination path
                    Storage::put($destinationFile, file_get_contents($sourceFile));
                }

                // Update the photo path to the storage path for the current image
                $car[$imageKey] = 'cars/images/' . basename($car[$imageKey]);
            }

            // Create the car record
            Car::create($car);
        }
    }
}
